//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Killer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        private string _image;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Agent()
        {
            this.Shipment = new HashSet<Shipment>();
        }
        public string type_agent { get; set; }
        public string name_agent { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string logotip {
            get
            {
                if (_image == null)
                {
                    return "Image/picture.png";
                }
                return _image;
            }
            set => _image = value;
        }
        
        public string andres { get; set; }
        public int prioritet { get; set; }
        public string director { get; set; }
        public string INN { get; set; }
        public string KPP { get; set; }
    
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shipment> Shipment { get; set; }
    }
}
