//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace USA_Killer.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment
    {
        public int id { get; set; }
        public string product { get; set; }
        public string agent { get; set; }
        public System.DateTime date { get; set; }
        public int count_product { get; set; }
    
        public virtual Agent Agent1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
